# Generated by Django 2.1.7 on 2019-03-20 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VK_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='item_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
